### ISSUE TITLE
Selenium Remote on LINUX: drivers path error

### ISSUE THREAD

**Issue by netzulo** [netzulo/ntzXagobah#2]
org.openqa.selenium.WebDriverException: **The driver executable does not exist: E:\qalab\%SELENIUM%\drivers\chromedriver.exe**
Command duration or timeout: 519 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: **'2016-03-15 16:57:40'**
System info: host: 'ntz-qa', ip: '10.0.0.27', os.name: **'Linux',** os.arch: **'amd64',** os.version: **'4.4.0-31-generic',** java.version: **'1.8.0_101'**
Driver info: org.openqa.selenium.remote.RemoteWebDriver

...

org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
    at org.testng.TestRunner.privateRun(TestRunner.java:774)
    at org.testng.TestRunner.run(TestRunner.java:624)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
    at org.testng.SuiteRunner.run(SuiteRunner.java:261)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
    at org.testng.TestNG.run(TestNG.java:1048)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.lang.IllegalStateException: **The driver executable does not exist: E:\qalab\%SELENIUM%\drivers\chromedriver.exe**

**Comment by netzulo** [comment]
#12 Relationship

**Comment by netzulo** [comment]
**Obsolete**
